# METAINFORMANT GWAS Configuration Template
# Genome-Wide Association Studies (GWAS) Pipeline Configuration

work_dir: output/gwas/work
log_dir: output/gwas/logs
threads: 8

# =============================================================================
# REFERENCE GENOME
# =============================================================================
# Reference genome configuration (reuses dna.ncbi infrastructure)
genome:
  # NCBI assembly accession (e.g., GCF_000001405.40 for human GRCh38)
  accession: GCF_000001405.40

  # Local destination directory for genome files
  dest_dir: output/gwas/genome

  # Files to download from NCBI (see: https://www.ncbi.nlm.nih.gov/datasets/docs/v2/)
  include:
    - genome         # Genomic sequences (FASTA)
    - gff3          # Gene annotations

  # Optional: specify FTP URL for direct download
  # ftp_url: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.40_GRCh38.p14/

# =============================================================================
# VARIANT DATA SOURCES
# =============================================================================
variants:
  # Option 1: Pre-called VCF file(s) - provide path(s) to existing VCF files
  vcf_files:
    # - data/variants/sample_set.vcf.gz
    # - data/variants/cohort.vcf.gz

  # Option 2: Download from public database
  download:
    # Source: dbSNP, 1000genomes, or custom
    source: dbSNP  # or: 1000genomes, custom
    accession: GCF_000001405.40
    # Optional: filter by genomic region (format: chr:start-end)
    # region: chr1:1000000-2000000

  # Option 3: Call variants from raw sequencing data (BAM/CRAM)
  calling:
    # List of BAM/CRAM file paths
    bam_files: []
    # Reference genome FASTA (if different from genome.dest_dir)
    reference: output/gwas/genome/genomic.fna
    # Calling method: bcftools, gatk, or freebayes
    method: bcftools  # or: gatk, freebayes

  # Destination directory for variant files
  dest_dir: output/gwas/variants

# =============================================================================
# QUALITY CONTROL
# =============================================================================
qc:
  # Minimum minor allele frequency (MAF) threshold
  min_maf: 0.01

  # Maximum missing genotype rate per variant
  max_missing: 0.05

  # Minimum call rate per variant
  min_call_rate: 0.95

  # Hardy-Weinberg equilibrium p-value threshold
  hwe_pval: 1e-6

  # Exclude insertion/deletion variants
  exclude_indels: true

  # Minimum variant quality score
  min_qual: 30.0

# =============================================================================
# SAMPLE METADATA
# =============================================================================
samples:
  # List of sample IDs (optional, if not provided, uses all samples in VCF)
  sample_list: data/samples.txt

  # Phenotype file (TSV format: sample_id, trait1, trait2, ...)
  phenotype_file: data/phenotypes.tsv

  # Covariates file (TSV format: sample_id, age, sex, PC1, PC2, ...)
  covariates_file: data/covariates.tsv

# =============================================================================
# POPULATION STRUCTURE
# =============================================================================
structure:
  # Compute principal components (PCA)
  compute_pca: true

  # Number of principal components to compute
  n_components: 10

  # Compute kinship/relatedness matrix
  compute_relatedness: true

  # Kinship computation method: vanraden, astle, or yang
  kinship_method: vanraden  # or: astle, yang

# =============================================================================
# ASSOCIATION TESTING
# =============================================================================
association:
  # Statistical model: linear, logistic, or mixed
  model: linear  # or: logistic, mixed

  # Trait name (column name in phenotype file)
  trait: trait1

  # Covariates to include in association model
  covariates:
    - age
    - sex
    - PC1
    - PC2
    - PC3

  # Minimum sample size required per variant
  min_sample_size: 50

  # Relatedness matrix: auto (use computed), or path to kinship matrix file
  relatedness_matrix: auto

# =============================================================================
# MULTIPLE TESTING CORRECTION
# =============================================================================
correction:
  # Correction method: bonferroni, fdr, both, or permutation
  method: bonferroni  # or: fdr, both

  # Significance level (alpha)
  alpha: 0.05

# =============================================================================
# OUTPUT
# =============================================================================
output:
  # Directory for association test results
  results_dir: output/gwas/results

  # Directory for visualization plots
  plots_dir: output/gwas/plots

  # Output format: json, tsv, or plink
  format: tsv  # or: json, plink

