work_dir: projects/hymenoptera_amalgkit/data/temnothorax_americanus/work
log_dir: projects/hymenoptera_amalgkit/data/temnothorax_americanus/logs
threads: 2
auto_install_amalgkit: true
filters:
  require_tissue: false
species_list:
- Temnothorax_americanus
taxon_id: 1964332
genome:
  accession: GCF_048541705.1
  assembly_name: ASM4854170v1
  annotation_release: RS_2025_09
  dest_dir: projects/hymenoptera_amalgkit/data/shared/genome/Temnothorax_americanus
  include:
  - genome
  - gff3
  - rna
  - cds
  - protein
  ftp_url: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/048/541/705/GCF_048541705.1_ASM4854170v1/
  files:
    genomic_fasta: GCF_048541705.1_ASM4854170v1_genomic.fna.gz
    transcriptome_fasta: GCF_048541705.1_ASM4854170v1_rna_from_genomic.fna.gz
    cds_fasta: GCF_048541705.1_ASM4854170v1_cds_from_genomic.fna.gz
    protein_fasta: GCF_048541705.1_ASM4854170v1_protein.faa.gz
    annotation_gff: GCF_048541705.1_ASM4854170v1_genomic.gff.gz
steps:
  metadata:
    out_dir: projects/hymenoptera_amalgkit/data/temnothorax_americanus/work
    search_string: '"Temnothorax americanus"[Organism] AND "RNA-Seq"[Strategy] AND
      "Illumina"[Platform]'
    redo: false
  integrate:
    fastq_dir: projects/hymenoptera_amalgkit/data/temnothorax_americanus/fastq/getfastq
  select:
    max_sample: 999999
    mark_missing_rank: none
    priority: completeness
    redo: false
  getfastq:
    out_dir: projects/hymenoptera_amalgkit/data/temnothorax_americanus/fastq
    threads: 2
    jobs: 2
    redo: false
    aws: true
    gcp: false
    ncbi: false
    pfd: true
    fastp: false
    max_bp: 50000000
  quant:
    jobs: 1
    out_dir: projects/hymenoptera_amalgkit/data/temnothorax_americanus/work
    threads: 2
    redo: false
    build_index: false
    keep_fastq: false
    index_dir: projects/hymenoptera_amalgkit/data/shared/genome/Temnothorax_americanus/index
    fasta_dir: projects/hymenoptera_amalgkit/data/shared/genome/Temnothorax_americanus
  merge:
    out: projects/hymenoptera_amalgkit/data/temnothorax_americanus/merged/merged_abundance.tsv
    out_dir: projects/hymenoptera_amalgkit/data/temnothorax_americanus/merged
  cstmm:
    out_dir: projects/hymenoptera_amalgkit/data/temnothorax_americanus/work
    orthogroup_table: ''
  curate:
    out_dir: projects/hymenoptera_amalgkit/data/temnothorax_americanus/work
  csca:
    out_dir: projects/hymenoptera_amalgkit/data/temnothorax_americanus/work
    orthogroup_table: ''
  sanity: {}
