work_dir: projects/hymenoptera_amalgkit/data/pogonomyrmex_barbatus/work
log_dir: projects/hymenoptera_amalgkit/data/pogonomyrmex_barbatus/logs
threads: 2
auto_install_amalgkit: true
filters:
  require_tissue: false
species_list:
- Pogonomyrmex_barbatus
taxon_id: 144034
genome:
  accession: GCF_000187915.1
  assembly_name: Pbar_UMD_V03
  annotation_release: 101
  dest_dir: projects/hymenoptera_amalgkit/data/shared/genome/Pogonomyrmex_barbatus
  include:
  - genome
  - gff3
  - rna
  - cds
  - protein
  ftp_url: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/187/915/GCF_000187915.1_Pbar_UMD_V03/
  files:
    genomic_fasta: GCF_000187915.1_Pbar_UMD_V03_genomic.fna.gz
    transcriptome_fasta: GCF_000187915.1_Pbar_UMD_V03_rna_from_genomic.fna.gz
    cds_fasta: GCF_000187915.1_Pbar_UMD_V03_cds_from_genomic.fna.gz
    protein_fasta: GCF_000187915.1_Pbar_UMD_V03_protein.faa.gz
    annotation_gff: GCF_000187915.1_Pbar_UMD_V03_genomic.gff.gz
steps:
  metadata:
    out_dir: projects/hymenoptera_amalgkit/data/pogonomyrmex_barbatus/work
    search_string: '"Pogonomyrmex barbatus"[Organism] AND "RNA-Seq"[Strategy] AND
      "Illumina"[Platform]'
    redo: false
  integrate:
    fastq_dir: projects/hymenoptera_amalgkit/data/pogonomyrmex_barbatus/fastq/getfastq
  select:
    max_sample: 999999
    mark_missing_rank: none
    priority: completeness
    redo: false
  getfastq:
    out_dir: projects/hymenoptera_amalgkit/data/pogonomyrmex_barbatus/fastq
    threads: 2
    jobs: 2
    redo: false
    aws: true
    gcp: false
    ncbi: false
    pfd: true
    fastp: false
    max_bp: 50000000
  quant:
    jobs: 1
    out_dir: projects/hymenoptera_amalgkit/data/pogonomyrmex_barbatus/work
    threads: 2
    redo: false
    build_index: false
    keep_fastq: false
    index_dir: projects/hymenoptera_amalgkit/data/shared/genome/Pogonomyrmex_barbatus/index
    fasta_dir: projects/hymenoptera_amalgkit/data/shared/genome/Pogonomyrmex_barbatus
  merge:
    out: projects/hymenoptera_amalgkit/data/pogonomyrmex_barbatus/merged/merged_abundance.tsv
    out_dir: projects/hymenoptera_amalgkit/data/pogonomyrmex_barbatus/merged
  cstmm:
    out_dir: projects/hymenoptera_amalgkit/data/pogonomyrmex_barbatus/work
    orthogroup_table: ''
  curate:
    out_dir: projects/hymenoptera_amalgkit/data/pogonomyrmex_barbatus/work
  csca:
    out_dir: projects/hymenoptera_amalgkit/data/pogonomyrmex_barbatus/work
    orthogroup_table: ''
  sanity: {}
