# METAINFORMANT Amalgkit Configuration
# Species: Camponotus floridanus (Florida Carpenter Ant)
# NCBI Taxonomy ID: 104421
# Assembly: GCF_003227725.1_Cflo_v7.5 (Cflo_v7.5)
# Sequencing: PacBio long-read sequencing, high-contiguity assembly
# Annotation Release: 101
# Notes: Model organism for epigenetics, caste determination, and aging research


work_dir: output/amalgkit/cfloridanus/work
log_dir: output/amalgkit/cfloridanus/logs
threads: 8


auto_install_amalgkit: true


# Pre-selection filtering rules
filters:
  require_tissue: false  # Changed to false to get all RNA-seq samples, not just those with tissue metadata


# Species configuration
species_list:
  - Camponotus_floridanus


# Alternative taxonomy specification
taxon_id: 104421


# Reference genome configuration
# Based on NCBI FTP: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/003/227/725/GCF_003227725.1_Cflo_v7.5/
genome:
  accession: GCF_003227725.1
  assembly_name: Cflo_v7.5
  annotation_release: 101
  dest_dir: output/amalgkit/cfloridanus/genome


  # Files to download (based on available NCBI FTP resources)
  include:
    - genome           # GCF_003227725.1_Cflo_v7.5_genomic.fna.gz
    - gff3            # GCF_003227725.1_Cflo_v7.5_genomic.gff.gz
    - rna             # GCF_003227725.1_Cflo_v7.5_rna_from_genomic.fna.gz
    - cds             # GCF_003227725.1_Cflo_v7.5_cds_from_genomic.fna.gz
    - protein         # GCF_003227725.1_Cflo_v7.5_protein.faa.gz
    - seq-report      # GCF_003227725.1_Cflo_v7.5_assembly_report.txt
    - feature-table   # GCF_003227725.1_Cflo_v7.5_feature_table.txt.gz
    - gene-ontology   # GCF_003227725.1_Cflo_v7.5_gene_ontology.gaf.gz


  # Direct FTP URL for all genome files
  ftp_url: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/003/227/725/GCF_003227725.1_Cflo_v7.5/


  # Specific important files for transcriptome analysis
  files:
    genomic_fasta: GCF_003227725.1_Cflo_v7.5_genomic.fna.gz
    transcriptome_fasta: GCF_003227725.1_Cflo_v7.5_rna_from_genomic.fna.gz
    cds_fasta: GCF_003227725.1_Cflo_v7.5_cds_from_genomic.fna.gz
    protein_fasta: GCF_003227725.1_Cflo_v7.5_protein.faa.gz
    annotation_gff: GCF_003227725.1_Cflo_v7.5_genomic.gff.gz
    annotation_gtf: GCF_003227725.1_Cflo_v7.5_genomic.gtf.gz


# Per-step parameters (merged on top of common params)
steps:
  metadata:
    # Required by amalgkit metadata
    out_dir: output/amalgkit/cfloridanus/work
    # Uses NCBI_EMAIL from environment; override here if needed
    # entrez_email: you@example.com
    search_string: '"Camponotus floridanus"[Organism] AND RNA-Seq[Strategy] AND Illumina[Platform]'
    redo: yes
  integrate:
    fastq_dir: output/amalgkit/cfloridanus/fastq
  config: {}
  select: {}
  getfastq:
    out_dir: output/amalgkit/cfloridanus/fastq
    threads: 8
    # Cloud acceleration via individual mirrors
    aws: yes
    gcp: yes
    ncbi: yes
    # pfd: yes         # DISABLED: parallel-fastq-dump failing, use fasterq-dump
  quant:
    # If a Salmon/Kallisto index is available, set it; otherwise genome_dir is injected from genome step
    out_dir: output/amalgkit/cfloridanus/quant
    threads: 8
    redo: no
    # Delete SRA/FASTQ files after quantification to save space
    keep_fastq: no
    # Build kallisto index if not present
    build_index: yes
  merge:
    out: output/amalgkit/cfloridanus/merged/merged_abundance.tsv
    out_dir: output/amalgkit/cfloridanus/merged
  cstmm:
    out_dir: output/amalgkit/cfloridanus/cstmm
  curate:
    out_dir: output/amalgkit/cfloridanus/curate
  csca:
    out_dir: output/amalgkit/cfloridanus/csca
  sanity: {}
