"""Amalgkit RNA-seq workflow module exports."""

from __future__ import annotations

from . import amalgkit, genome_prep, index_prep, metadata_filter, metadata_utils, tissue_normalizer

# Expose core functions from amalgkit.py at package level for convenience
from .amalgkit import (
    AMALGKIT_INSTALL_SPEC,
    AMALGKIT_RELEASE_TAG,
    AMALGKIT_SOURCE_REVISION,
    REQUIRED_AMALGKIT_VERSION,
    AmalgkitParams,
    build_amalgkit_command,
    build_cli_args,
    busco,
    check_cli_available,
    csfilter,
    cstmm,
    dataset,
    ensure_cli_available,
    finalize,
    getfastq,
    integrate,
    merge,
    metadata,
    parse_and_check_version,
    quant,
    rerun,
    run_amalgkit,
    sanity,
    select,
    validate_amalgkit_version,
    wsfilter,
)

__all__ = [
    "amalgkit",
    "genome_prep",
    "index_prep",
    "metadata_filter",
    "metadata_utils",
    "tissue_normalizer",
    "AMALGKIT_INSTALL_SPEC",
    "AMALGKIT_RELEASE_TAG",
    "AMALGKIT_SOURCE_REVISION",
    "REQUIRED_AMALGKIT_VERSION",
    "AmalgkitParams",
    "build_amalgkit_command",
    "build_cli_args",
    "busco",
    "check_cli_available",
    "csfilter",
    "cstmm",
    "ensure_cli_available",
    "finalize",
    "getfastq",
    "integrate",
    "merge",
    "metadata",
    "parse_and_check_version",
    "quant",
    "rerun",
    "run_amalgkit",
    "sanity",
    "select",
    "dataset",
    "validate_amalgkit_version",
    "wsfilter",
]
