"""Campaign-local subprocess environments for SRA and FASTQ tooling."""

from __future__ import annotations

import os
import threading
from pathlib import Path
from typing import Mapping

_SETTINGS_LOCK = threading.Lock()


def resolve_data_root(data_root: str | Path | None = None) -> Path:
    """Resolve the campaign data root without consulting user-global state."""

    if data_root is not None:
        return Path(data_root).expanduser()
    return Path(os.environ.get("AMALGKIT_DATA_ROOT", "output/amalgkit")).expanduser()


def ensure_ncbi_settings(data_root: str | Path | None = None) -> Path:
    """Create the deterministic campaign-local NCBI settings file."""

    override = os.environ.get("AMALGKIT_NCBI_SETTINGS", "").strip()
    if override:
        return Path(override).expanduser().resolve()

    root = resolve_data_root(data_root).resolve()
    settings_dir = root / ".ncbi"
    settings_path = settings_dir / "metainformant-user-settings.mkfg"
    sra_root = root / ".sra-cache"
    payload = (
        "## Generated by MetaInformAnt RNA orchestration.\n"
        "## Keep SRA fallback caches with the campaign data root.\n"
        f'/repository/user/main/public/root = "{sra_root}"\n'
    )

    with _SETTINGS_LOCK:
        settings_dir.mkdir(parents=True, exist_ok=True)
        sra_root.mkdir(parents=True, exist_ok=True)
        if not settings_path.is_file() or settings_path.read_text(encoding="utf-8") != payload:
            temporary = settings_path.with_name(f".{settings_path.name}.tmp-{os.getpid()}-{threading.get_ident()}")
            temporary.write_text(payload, encoding="utf-8")
            os.replace(temporary, settings_path)
    return settings_path


def build_sra_environment(
    data_root: str | Path | None = None,
    *,
    base_environment: Mapping[str, str] | None = None,
) -> dict[str, str]:
    """Return an inherited environment scoped to one campaign data root."""

    # Keep the public workflow path resolver compatible with relative command
    # paths, but make every subprocess-owned directory absolute and CWD-safe.
    root = resolve_data_root(data_root).resolve()
    environment = dict(os.environ if base_environment is None else base_environment)
    runtime_root = root / ".metainformant" / "sra"
    tmp_dir = runtime_root / "fasterq-dump"
    vdb_cache = runtime_root / "vdb"
    tmp_dir.mkdir(parents=True, exist_ok=True)
    vdb_cache.mkdir(parents=True, exist_ok=True)
    environment["NCBI_SETTINGS"] = str(ensure_ncbi_settings(root))
    environment["TMPDIR"] = str(tmp_dir)
    environment["VDB_CONFIG"] = str(vdb_cache)
    return environment
