"""Core Input/Output utilities for METAINFORMANT.

This module provides a unified interface for file operations, caching,
downloads, and disk management.
"""

from .atomic import (
    atomic_replace,
    atomic_write,
    safe_write_bytes,
    safe_write_text,
    temp_directory,
)
from .cache import (
    CacheEntry,
    JsonCache,
    cache_json,
    clear_cache_dir,
    get_cache_info,
    load_cached_json,
)
from .checksums import (
    compute_checksums_batch,
    compute_md5,
    compute_sha256,
    verify_checksum,
    verify_checksum_file,
    write_checksum_file,
)
from .disk import (
    check_disk_space,
    cleanup_old_files,
    cleanup_temp_files,
    detect_drive_size_category,
    ensure_disk_space,
    get_directory_size,
    get_disk_space_info,
    get_disk_usage,
    get_free_space,
    get_largest_files,
    get_recommended_batch_size,
    get_recommended_temp_dir,
    monitor_disk_space,
    safe_remove_directory,
)
from .errors import (
    CacheError,
    DownloadError,
    FileNotFoundError,
    IOError,
)
from .io import (
    batch_download,
    download_csv,
    download_file,
    download_json,
    download_text,
    dump_json,
    dump_json_gz,
    dump_yaml,
    ensure_directory,
    load_json,
    load_json_gz,
    load_toml,
    load_yaml,
    open_text_auto,
    read_csv,
    read_delimited,
    read_jsonl,
    read_parquet,
    read_tsv,
    write_csv,
    write_delimited,
    write_jsonl,
    write_parquet,
    write_tsv,
)
from .paths import (
    get_cache_dir,
    get_data_dir,
    get_logs_dir,
    get_project_root,
    get_temp_dir,
    is_safe_path,
    resolve_path,
)

__all__ = [
    # Errors
    "IOError",
    "FileNotFoundError",
    "CacheError",
    "DownloadError",
    # IO
    "ensure_directory",
    "open_text_auto",
    "load_json",
    "dump_json",
    "dump_json_gz",
    "load_json_gz",
    "load_yaml",
    "load_toml",
    "dump_yaml",
    "read_parquet",
    "write_parquet",
    "read_jsonl",
    "write_jsonl",
    "read_delimited",
    "write_delimited",
    "read_csv",
    "write_csv",
    "read_tsv",
    "write_tsv",
    "download_file",
    "download_json",
    "download_text",
    "download_csv",
    "batch_download",
    # Cache
    "JsonCache",
    "CacheEntry",
    "get_cache_info",
    "cache_json",
    "load_cached_json",
    "clear_cache_dir",
    # Disk
    "get_disk_usage",
    "get_free_space",
    "get_recommended_temp_dir",
    "ensure_disk_space",
    "check_disk_space",
    "cleanup_temp_files",
    "cleanup_old_files",
    "get_directory_size",
    "get_largest_files",
    "monitor_disk_space",
    "safe_remove_directory",
    "get_disk_space_info",
    "detect_drive_size_category",
    "get_recommended_batch_size",
    # Atomic
    "atomic_replace",
    "atomic_write",
    "safe_write_bytes",
    "safe_write_text",
    "temp_directory",
    # Checksums
    "compute_checksums_batch",
    "compute_md5",
    "compute_sha256",
    "verify_checksum",
    "verify_checksum_file",
    "write_checksum_file",
    # Paths
    "get_project_root",
    "get_data_dir",
    "get_cache_dir",
    "get_logs_dir",
    "get_temp_dir",
    "resolve_path",
    "is_safe_path",
]
