"""Internal campaign-local environments for SRA command-line tools.

The helper is intentionally private at the core layer.  Domain modules expose
their documented wrappers while sharing one implementation for ``NCBI_SETTINGS``,
``TMPDIR``, ``VDB_CONFIG``, and SRA cache placement.
"""

from __future__ import annotations

import os
import threading
from pathlib import Path
from typing import Mapping

_SETTINGS_LOCK = threading.Lock()


def _resolve_data_root(data_root: str | Path | None = None) -> Path:
    """Resolve a campaign root without consulting user-global SRA state.

    Delegates to the canonical :func:`metainformant.core.io.data_root.resolve_data_root`.
    """
    from metainformant.core.io.data_root import resolve_data_root

    return resolve_data_root(data_root)


def _ensure_ncbi_settings(data_root: str | Path | None = None) -> Path:
    """Create or reuse deterministic campaign-local NCBI settings."""

    override = os.environ.get("AMALGKIT_NCBI_SETTINGS", "").strip()
    if override:
        return Path(override).expanduser().resolve()

    root = _resolve_data_root(data_root).resolve()
    settings_dir = root / ".ncbi"
    settings_path = settings_dir / "metainformant-user-settings.mkfg"
    sra_root = root / ".sra-cache"
    payload = (
        "## Generated by MetaInformAnt RNA orchestration.\n"
        "## Keep SRA fallback caches with the campaign data root.\n"
        f'/repository/user/main/public/root = "{sra_root}"\n'
    )

    with _SETTINGS_LOCK:
        settings_dir.mkdir(parents=True, exist_ok=True)
        sra_root.mkdir(parents=True, exist_ok=True)
        if not settings_path.is_file() or settings_path.read_text(encoding="utf-8") != payload:
            temporary = settings_path.with_name(f".{settings_path.name}.tmp-{os.getpid()}-{threading.get_ident()}")
            temporary.write_text(payload, encoding="utf-8")
            os.replace(temporary, settings_path)
    return settings_path


def _build_sra_environment(
    data_root: str | Path | None = None,
    *,
    base_environment: Mapping[str, str] | None = None,
) -> dict[str, str]:
    """Build an inherited environment scoped to one campaign root."""

    # Keep public workflow path resolution compatible with relative command
    # paths, but make subprocess-owned directories absolute and CWD-safe.
    root = _resolve_data_root(data_root).resolve()
    environment = dict(os.environ if base_environment is None else base_environment)
    runtime_root = root / ".metainformant" / "sra"
    tmp_dir = runtime_root / "fasterq-dump"
    vdb_cache = runtime_root / "vdb"
    tmp_dir.mkdir(parents=True, exist_ok=True)
    vdb_cache.mkdir(parents=True, exist_ok=True)
    environment["NCBI_SETTINGS"] = str(_ensure_ncbi_settings(root))
    environment["TMPDIR"] = str(tmp_dir)
    environment["VDB_CONFIG"] = str(vdb_cache)
    return environment
