from __future__ import annotations

import subprocess
import sys
from pathlib import Path


def test_selection_replay_writes_outputs(tmp_path: Path) -> None:
    dest = tmp_path / "selection_experiments"
    cmd = [
        sys.executable,
        "-m",
        "metainformant",
        "math",
        "selection",
        "replay",
        "--dest",
        str(dest),
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    assert result.returncode == 0, result.stderr
    # Expect the figures generated by the replay in outputs subfolder
    outputs_dir = dest / "outputs"
    expected = [
        "plot-s-vs-q.png",
        "plot-sq-vs-w.png",
        "plot-ns-rebound.png",
        "plot-ns-inverse.png",
        "plot-ns.png",
        "plot-ns-qsl.png",
    ]
    for name in expected:
        path = outputs_dir / name
        assert path.exists(), f"missing {path}"
        assert path.stat().st_size > 0


