#!/bin/bash
# View progress dashboard if available

DASHBOARD_FILE="output/amalgkit/progress_dashboard.txt"
PNG_FILE="output/amalgkit/progress_dashboard.png"

echo "📊 Checking for progress dashboard..."
echo ""

if [ -f "$DASHBOARD_FILE" ]; then
    echo "✅ Text dashboard found: $DASHBOARD_FILE"
    echo ""
    cat "$DASHBOARD_FILE"
    echo ""
else
    echo "⚠️  Text dashboard not found: $DASHBOARD_FILE"
    echo "   (Dashboard is generated by ProgressTracker when workflow events occur)"
fi

if [ -f "$PNG_FILE" ]; then
    echo "✅ PNG visualization found: $PNG_FILE"
    echo "   Open with: xdg-open $PNG_FILE  (or your image viewer)"
else
    echo "⚠️  PNG visualization not found: $PNG_FILE"
fi

