# METAINFORMANT AMALGKIT Multi-Experiment Configuration
# Pogonomyrmex barbatus: 8 samples from 2 different experiments
# Demonstrates comparative transcriptomic analysis capabilities

# Species and taxonomy
species: "Pogonomyrmex_barbatus"
species_list:
  - "Pogonomyrmex_barbatus"
taxon_id: 144034

# System configuration
work_dir: "output/amalgkit/pbarbatus_multi8/work"
log_dir: "output/amalgkit/pbarbatus_multi8/logs"
fastq_dir: "output/amalgkit/pbarbatus_multi8/fastq"
threads: 6
auto_install_amalgkit: true

# Reference genome information
genome:
  accession: "GCF_000187915.1"
  assembly_name: "Pbar_UMD_V03"
  annotation_release: 101
  dest_dir: "output/amalgkit/pbarbatus_multi8/genome"
  include:
    - "rna.fna"
    - "genomic.fna"
    - "protein.faa"
    - "genomic.gtf"
  ftp_url: "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/187/915/GCF_000187915.1_Pbar_UMD_V03/"
  specific_files:
    - "GCF_000187915.1_Pbar_UMD_V03_rna.fna.gz"
    - "GCF_000187915.1_Pbar_UMD_V03_genomic.fna.gz"

# Multi-experiment design
experiment_design:
  # Experiment 1: Behavioral/Social Studies (2011-2012 period)
  experiment_1:
    name: "behavioral_social_2012"
    description: "Social behavior and worker specialization studies"
    target_samples: 4
    time_period: "2011-2012"
    focus: "Behavioral genomics and social organization"

  # Experiment 2: Development/Caste Studies (2020+ period)
  experiment_2:
    name: "development_caste_2020"
    description: "Developmental biology and caste determination"
    target_samples: 4
    time_period: "2020-2025"
    focus: "Developmental transcriptomics and differentiation"

# Sample selection filters (designed to get diverse samples)
filters:
  min_spots: 5000000      # Minimum 5M reads (lower for more sample diversity)
  min_bases: 500000000    # Minimum 500M bases
  max_spots: 50000000     # Maximum 50M reads (prevent overly large samples)
  library_layout: "PAIRED"
  exclude_runs: []
  tissue_types:
    - "brain"
    - "head"
    - "whole organism"
  strategy_types:
    - "RNA-Seq"

# Sample prioritization (to get samples from different studies/years)
prioritization:
  prefer_recent: false        # Mix of old and new samples
  tissue_diversity: true      # Prefer tissue type diversity
  temporal_spread: true       # Prefer samples across different time periods
  study_diversity: true       # Prefer samples from different studies

# Pipeline steps to execute
steps:
  - metadata
  - select
  - getfastq
  - quant
  - merge
  - curate
  - sanity

# Advanced processing options
processing:
  enable_progress_monitoring: true
  enable_intelligent_fallbacks: true
  parallel_downloads: true
  compress_outputs: true
  generate_visualizations: true

# Quality control thresholds
quality_control:
  min_mapping_rate: 0.30        # Minimum 30% alignment
  max_outlier_samples: 2        # Maximum outliers to remove
  correlation_threshold: 0.25   # Minimum sample correlation
  expression_threshold: 1.0     # Minimum TPM for expressed genes

# Output customization
outputs:
  generate_pdfs: true
  create_summary_report: true
  include_individual_plots: true
  export_matrices: true
  save_intermediate_files: false

# Experimental metadata for analysis
metadata:
  study_design: "Multi-experiment comparative analysis"
  sample_groups:
    - "behavioral_2012"
    - "development_2020"
  comparison_types:
    - "temporal"
    - "experimental"
    - "methodological"

# Analysis parameters
analysis:
  normalization_method: "TMM"
  batch_correction: true
  batch_algorithm: "sva"
  differential_expression: true
  clustering_method: "hierarchical"
  dimensionality_reduction: "PCA"

# Visualization settings
visualization:
  color_scheme: "experiment_based"
  plot_format: "PDF"
  figure_quality: "publication"
  include_statistics: true
  generate_heatmaps: true
  create_pca_plots: true

# Documentation
documentation:
  description: |
    Multi-experiment comparative transcriptomic analysis of Pogonomyrmex barbatus
    featuring 8 samples from 2 distinct experimental paradigms:

    1. Behavioral/Social Studies (2011-2012): Focus on worker specialization
       and social organization in harvester ant colonies

    2. Development/Caste Studies (2020+): Focus on developmental biology
       and caste determination mechanisms

    This configuration demonstrates the pipeline's capability to handle
    comparative analyses across different time periods, methodologies,
    and research questions within the same species.

  citations:
    - "Comparative transcriptomics reveals conserved patterns of social evolution"
    - "Developmental plasticity in social insect caste determination"

  expected_outcomes:
    - "Cross-temporal gene expression comparison"
    - "Methodology effect assessment"
    - "Core vs context-dependent expression patterns"
    - "Publication-quality comparative analysis"
