# Comprehensive amalgkit run configuration
# Species: Pogonomyrmex barbatus (NCBI:txid144034)

work_dir: output/amalgkit/pbarbatus/work
log_dir: output/amalgkit/pbarbatus/logs
threads: 6

auto_install_amalgkit: true

# Apply pre-selection filtering rules
filters:
  require_tissue: true

# Common filters
species_list:
  - Pogonomyrmex_barbatus
# Alternatively, you could specify taxonomy id if supported by your amalgkit build:
# taxon_id: 144034

# Genome package retrieval (best-effort via CLI/API/FTP)
genome:
  accession: GCF_000187915.1
  dest_dir: output/amalgkit/pbarbatus/genome
  include: [genome, gff3, rna, cds, protein, seq-report]
  ftp_url: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/187/915/GCF_000187915.1_Pbar_UMD_V03/

# Per-step parameters (merged on top of common params)
steps:
  metadata:
    # Required by amalgkit metadata
    out_dir: output/amalgkit/pbarbatus/work
    # Uses NCBI_EMAIL from environment; override here if needed
    # entrez_email: you@example.com
    search_string: '"Pogonomyrmex barbatus"[Organism] AND RNA-Seq[Strategy] AND Illumina[Platform]'
    redo: yes
  integrate: {}
  config: {}
  select: {}
  integrate:
    fastq_dir: output/amalgkit/pbarbatus/fastq
  getfastq:
    out_dir: output/amalgkit/pbarbatus/fastq
  quant:
    # If a Salmon/Kallisto index is available, set it; otherwise genome_dir is injected from genome step
    out_dir: output/amalgkit/pbarbatus/quant
    threads: 6
  merge:
    out: output/amalgkit/pbarbatus/merged/merged_abundance.tsv
  cstmm:
    out_dir: output/amalgkit/pbarbatus/cstmm
  curate:
    out_dir: output/amalgkit/pbarbatus/curate
  csca:
    out_dir: output/amalgkit/pbarbatus/csca
  sanity: {}
