# METAINFORMANT Amalgkit Configuration - Test Mode
# Species: Pogonomyrmex barbatus (Red Harvester Ant)
# Test configuration for verification

work_dir: output/amalgkit/pbarbatus_test/work
log_dir: output/amalgkit/pbarbatus_test/logs
threads: 2

auto_install_amalgkit: true

# Species configuration
species_list:
  - Pogonomyrmex_barbatus

# Reference genome configuration
genome:
  accession: GCF_000187915.1
  assembly_name: Pbar_UMD_V03
  annotation_release: 101
  dest_dir: output/amalgkit/pbarbatus_test/genome

  # Files to download
  include:
    - genome
    - gff3
    - rna
    - cds
    - protein
    - seq-report

  ftp_url: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/187/915/GCF_000187915.1_Pbar_UMD_V03/

# Steps to execute
steps:
  metadata:
    out_dir: output/amalgkit/pbarbatus_test/work
    search_string: '"Pogonomyrmex barbatus"[Organism] AND RNA-Seq[Strategy] AND Illumina[Platform]'
    redo: yes
  config:
    out_dir: output/amalgkit/pbarbatus_test/work
  select:
    out_dir: output/amalgkit/pbarbatus_test/work
    # Select first 2 samples for testing
    max_sample: 2
    min_nspots: 10000000
  getfastq:
    out_dir: output/amalgkit/pbarbatus_test/fastq
  quant:
    out_dir: output/amalgkit/pbarbatus_test/quant
    threads: 2
  merge:
    out: output/amalgkit/pbarbatus_test/merged/merged_abundance.tsv
  sanity: {}
