# METAINFORMANT Amalgkit Configuration - Direct Download
# Species: Pogonomyrmex barbatus (Red Harvester Ant)
# Direct download of specific samples for testing

work_dir: output/amalgkit/pbarbatus_direct/work
log_dir: output/amalgkit/pbarbatus_direct/logs
threads: 4

auto_install_amalgkit: true

# Species configuration
species_list:
  - Pogonomyrmex_barbatus

# Reference genome configuration
genome:
  accession: GCF_000187915.1
  assembly_name: Pbar_UMD_V03
  annotation_release: 101
  dest_dir: output/amalgkit/pbarbatus_direct/genome

  # Files to download
  include:
    - genome
    - gff3
    - rna
    - cds
    - protein
    - seq-report

  ftp_url: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/187/915/GCF_000187915.1_Pbar_UMD_V03/

# Steps to execute
steps:
  config:
    out_dir: output/amalgkit/pbarbatus_direct/work
  getfastq:
    out_dir: output/amalgkit/pbarbatus_direct/fastq
    # Download specific samples directly
    id: ["SRR14740487", "SRR14740488"]
    # Clean up raw files after quantification
    cleanup_raw: yes
    # Use fastp for quality control
    fastp: yes
    fastp_exe: fastp
  quant:
    out_dir: output/amalgkit/pbarbatus_direct/quant
    threads: 4
    fasta_dir: output/amalgkit/pbarbatus_direct/fasta
    build_index: yes
  merge:
    out: output/amalgkit/pbarbatus_direct/merged/merged_abundance.tsv
  sanity: {}
