# METAINFORMANT Amalgkit Configuration
# Species: Pogonomyrmex barbatus (Red Harvester Ant)
# NCBI Taxonomy ID: 144034
# Assembly: GCF_000187915.1_Pbar_UMD_V03 (Pbar_UMD_V03)
# Sequencing: 454 pyrosequencing, high-quality assembly
# Annotation Release: 101

work_dir: output/amalgkit/pbarbatus/work
log_dir: output/amalgkit/pbarbatus/logs
threads: 6

auto_install_amalgkit: true

# Pre-selection filtering rules
filters:
  require_tissue: true
  # Additional filters for high-quality data
  platform: Illumina
  strategy: RNA-Seq
  min_read_length: 50
  min_spots: 10000000    # 10M spots minimum to include the samples we found
  max_spots: 40000000    # 40M spots maximum
  library_layout: PAIRED

# Species configuration
species_list:
  - Pogonomyrmex_barbatus

# Alternative taxonomy specification
taxon_id: 144034

# Reference genome configuration
# Based on NCBI FTP: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/187/915/GCF_000187915.1_Pbar_UMD_V03/
genome:
  accession: GCF_000187915.1
  assembly_name: Pbar_UMD_V03
  annotation_release: 101
  dest_dir: output/amalgkit/pbarbatus/genome

  # Files to download (based on available NCBI FTP resources)
  include:
    - genome           # GCF_000187915.1_Pbar_UMD_V03_genomic.fna.gz (68M)
    - gff3            # GCF_000187915.1_Pbar_UMD_V03_genomic.gff.gz (4.9M)
    - rna             # GCF_000187915.1_Pbar_UMD_V03_rna_from_genomic.fna.gz (11M)
    - cds             # GCF_000187915.1_Pbar_UMD_V03_cds_from_genomic.fna.gz (7.7M)
    - protein         # GCF_000187915.1_Pbar_UMD_V03_protein.faa.gz (4.5M)
    - seq-report      # GCF_000187915.1_Pbar_UMD_V03_assembly_report.txt
    - feature-table   # GCF_000187915.1_Pbar_UMD_V03_feature_table.txt.gz
    - gene-ontology   # GCF_000187915.1_Pbar_UMD_V03_gene_ontology.gaf.gz

  # Direct FTP URL for all genome files
  ftp_url: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/187/915/GCF_000187915.1_Pbar_UMD_V03/

  # Specific important files for transcriptome analysis
  files:
    genomic_fasta: GCF_000187915.1_Pbar_UMD_V03_genomic.fna.gz
    transcriptome_fasta: GCF_000187915.1_Pbar_UMD_V03_rna_from_genomic.fna.gz
    cds_fasta: GCF_000187915.1_Pbar_UMD_V03_cds_from_genomic.fna.gz
    protein_fasta: GCF_000187915.1_Pbar_UMD_V03_protein.faa.gz
    annotation_gff: GCF_000187915.1_Pbar_UMD_V03_genomic.gff.gz
    annotation_gtf: GCF_000187915.1_Pbar_UMD_V03_genomic.gtf.gz

# Per-step parameters (merged on top of common params)
steps:
  metadata:
    # Required by amalgkit metadata
    out_dir: output/amalgkit/pbarbatus/work
    # Uses NCBI_EMAIL from environment; override here if needed
    # entrez_email: you@example.com
    search_string: '"Pogonomyrmex barbatus"[Organism] AND RNA-Seq[Strategy] AND Illumina[Platform]'
    redo: yes
  integrate:
    fastq_dir: output/amalgkit/pbarbatus/fastq
  config: {}
  select: {}
  getfastq:
    out_dir: output/amalgkit/pbarbatus/fastq
  quant:
    # If a Salmon/Kallisto index is available, set it; otherwise genome_dir is injected from genome step
    out_dir: output/amalgkit/pbarbatus/quant
    threads: 6
  merge:
    out: output/amalgkit/pbarbatus/merged/merged_abundance.tsv
  cstmm:
    out_dir: output/amalgkit/pbarbatus/cstmm
  curate:
    out_dir: output/amalgkit/pbarbatus/curate
  csca:
    out_dir: output/amalgkit/pbarbatus/csca
  sanity: {}
