# METAINFORMANT Amalgkit Configuration - Manual Sample Selection
# Species: Pogonomyrmex barbatus (Red Harvester Ant)
# Manual selection of samples to avoid filtering issues

work_dir: output/amalgkit/pbarbatus_manual/work
log_dir: output/amalgkit/pbarbatus_manual/logs
threads: 4

auto_install_amalgkit: true

# Species configuration
species_list:
  - Pogonomyrmex_barbatus

# Reference genome configuration
genome:
  accession: GCF_000187915.1
  assembly_name: Pbar_UMD_V03
  annotation_release: 101
  dest_dir: output/amalgkit/pbarbatus_manual/genome

  # Files to download
  include:
    - genome
    - gff3
    - rna
    - cds
    - protein
    - seq-report

  ftp_url: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/187/915/GCF_000187915.1_Pbar_UMD_V03/

# Steps to execute
steps:
  metadata:
    out_dir: output/amalgkit/pbarbatus_manual/work
    search_string: '"Pogonomyrmex barbatus"[Organism] AND RNA-Seq[Strategy] AND Illumina[Platform]'
    redo: yes
  config:
    out_dir: output/amalgkit/pbarbatus_manual/work
  select:
    out_dir: output/amalgkit/pbarbatus_manual/work
    # Select specific samples manually
    id: ["SRR14740487", "SRR14740488"]
  getfastq:
    out_dir: output/amalgkit/pbarbatus_manual/fastq
    # Clean up raw files after quantification
    cleanup_raw: yes
    # Use fastp for quality control
    fastp: yes
    fastp_exe: fastp
  quant:
    out_dir: output/amalgkit/pbarbatus_manual/quant
    threads: 4
    # Use salmon for quantification
    method: salmon
  merge:
    out: output/amalgkit/pbarbatus_manual/merged/merged_abundance.tsv
  sanity: {}

