#!/usr/bin/env python3
"""Generate tests/README.md module map from the live test tree.

Regenerates the "Module map" table (module -> test dir -> file count ->
last-known pytest status) so the documentation cannot drift from the tree.
Writes only tests/README.md; everything outside the BEGIN/END markers is
preserved verbatim.

Modes:
    default      regenerate tests/README.md in place
    --check      verify the generated content matches the file; exit 1 on drift
    --json PATH  also write the collected map as JSON (for CI artifacts)

Usage:
    uv run python scripts/test/generate_tests_readme.py
    uv run python scripts/test/generate_tests_readme.py --check
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional

REPO_ROOT = Path(__file__).resolve().parents[2]
TESTS_DIR = REPO_ROOT / "tests"
README_PATH = TESTS_DIR / "README.md"

BEGIN = "<!-- BEGIN:TESTS_MODULE_MAP -->"
END = "<!-- END:TESTS_MODULE_MAP -->"

NON_MODULE_DIRS = {
    "__pycache__",
    "_support",
    "data",
    "fixtures",
    "infrastructure",
    "integration",
    "other",
    "scripts",
    "cstmm_fixture",
}

# Human-facing description per module (module name -> description).
DESCRIPTIONS = {
    "cloud": "Cloud deployment helpers",
    "core": "Core utilities",
    "dna": "DNA analysis",
    "ecology": "Ecological analysis",
    "epigenome": "Epigenomics",
    "gwas": "GWAS pipeline",
    "information": "Information theory",
    "life_events": "Life events",
    "longread": "Long-read sequencing",
    "math": "Mathematical biology / popgen",
    "mcp": "MCP server and tools",
    "menu": "Menu / CLI",
    "metabolomics": "Metabolomics",
    "metagenomics": "Metagenomics",
    "ml": "Machine learning",
    "multiomics": "Multi-omics integration",
    "networks": "Network analysis",
    "ontology": "Ontology / GO",
    "pharmacogenomics": "Pharmacogenomics",
    "phenotype": "Phenotype analysis",
    "protein": "Protein analysis",
    "quality": "Quality control",
    "rna": "RNA-seq workflows",
    "simulation": "Simulation",
    "singlecell": "Single-cell",
    "spatial": "Spatial transcriptomics",
    "structural_variants": "Structural variants",
    "visualization": "Visualization",
    "perf": "Performance benchmarks (opt-in)",
}


@dataclass
class ModuleRow:
    """One row of the generated module map."""

    module: str
    test_files: int
    test_functions: int

    def to_row(self) -> str:
        desc = DESCRIPTIONS.get(self.module, "")
        return (
            f"| [`tests/{self.module}/`](../tests/{self.module}/) | {desc} | "
            f"{self.test_files} | {self.test_functions} |"
        )


def collect_rows() -> List[ModuleRow]:
    """Scan the tests/ tree and collect per-module counts."""
    rows: List[ModuleRow] = []
    for entry in sorted(TESTS_DIR.iterdir()):
        if not (entry.is_dir() and entry.name not in NON_MODULE_DIRS):
            continue
        test_files = sorted(entry.glob("test_*.py"))
        if not test_files:
            continue
        # Count test functions without importing: lexical scan of defs.
        n_funcs = 0
        for tf in test_files:
            for line in tf.read_text(errors="replace").splitlines():
                stripped = line.strip()
                if stripped.startswith("def test_") or stripped.startswith("async def test_"):
                    n_funcs += 1
        rows.append(ModuleRow(module=entry.name, test_files=len(test_files), test_functions=n_funcs))
    return rows


def render_block(rows: List[ModuleRow]) -> str:
    lines = [
        BEGIN,
        "Module map generated by `scripts/test/generate_tests_readme.py` - regenerate, do not hand-edit.",
        "",
        "| Test dir | Module | Test files | Test functions |",
        "| --- | --- | ---: | ---: |",
    ]
    lines.extend(r.to_row() for r in rows)
    total_files = sum(r.test_files for r in rows)
    total_funcs = sum(r.test_functions for r in rows)
    lines.append(f"| **Total** | **{len(rows)} modules** | **{total_files}** | **{total_funcs}** |")
    lines.append(END)
    return "\n".join(lines)


def main(argv: Optional[List[str]] = None) -> int:
    """CLI entry point."""
    parser = argparse.ArgumentParser(description="Generate the tests/README.md module map")
    parser.add_argument("--check", action="store_true", help="verify the file matches generated content")
    parser.add_argument("--json", dest="json_path", default=None, help="also write the map as JSON")
    args = parser.parse_args(argv)

    rows = collect_rows()
    block = render_block(rows)

    if args.json_path:
        payload = {
            "modules": [
                {"module": r.module, "test_files": r.test_files, "test_functions": r.test_functions} for r in rows
            ]
        }
        Path(args.json_path).write_text(json.dumps(payload, indent=2) + "\n")

    if args.check:
        current = README_PATH.read_text()
        if BEGIN not in current or END not in current:
            print("FAIL: tests/README.md is missing the module-map markers", file=sys.stderr)
            return 1
        start = current.index(BEGIN)
        stop = current.index(END) + len(END)
        if current[start:stop] == block:
            print("OK: tests/README.md module map is up to date")
            return 0
        print("FAIL: tests/README.md module map is stale; regenerate it", file=sys.stderr)
        return 1

    current = README_PATH.read_text() if README_PATH.exists() else ""
    if BEGIN in current and END in current:
        start = current.index(BEGIN)
        stop = current.index(END) + len(END)
        updated = current[:start] + block + current[stop:]
    else:
        updated = (current.rstrip() + "\n\n" if current else "") + block + "\n"
    README_PATH.write_text(updated)
    print(f"Wrote {README_PATH} ({len(rows)} modules)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
